# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a2d54794603f6d71484f857b6445a938682354c2240c56bc6c893f51a48c6da433827d6772747ff7b8e1f08ed4ea69e04df1caa46300191c46b105440651785

test:
  secret_key_base: ddcb0c88b8199f10d03b8dfdf647971c7abb66caa5a704777cbf128244a89a3b9be72d8d1b60dceba32d8582bbbb40672bb7ff0c3e75f5d5a344e2e516ad8024

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
